import { ITheme } from "./themeTypes";

export const LightTheme: ITheme = {
        name: "light",
        dark: false,
        colors: {
                primary: "#10CEB3",
                primaryBackground: "#10CEB333",
                background: "#F8FAFC",
                card: "#FFFFFF",
                border: "#E2E8F0",
                textPrimary: "#0F172A",
                textSecondary: "#64748B",
                placeholder: "#94A3B8",
                lightBackground: 'rgba(0,255,200,0.08)',
                textViewBorder: "#195352",
                secondary: "#F1F5F9",
                secondaryText: "#0F172A",
                secondaryBackground: '#F2F8FA',
                success: "#22C55E",
                warning: "#F59E0B",
                error: "#EF4444",
                info: "#06B6D4",
                white: "#FFFFFF",
                black: "#000000",
                grey: "#808080",
                grayLight: "#D3D3D3",
                grayDark: "#A9A9A9",
                interestSelectorBg: '#9ce8db',
                cancel: '#FB7185',
                cancelBackground: '#FB718533',
                chatIcon: '#18263D',
                hotelIcon: '#FBBF23',
                hotelIconBackground: '#FBBF2333',
                danger: '#FF3E76',
                dangerBackground: '#FF3E7633',
                star:'#FDBA12',
        },
};

export const DarkTheme: ITheme = {
        name: "dark",
        dark: true,
        colors: {
                primary: "#10CEB3",
                primaryBackground: "#10CEB333",
                background: "#0A1220",
                card: "#101D30",
                border: "#1E2C42",
                textPrimary: "#F8FAFC",
                textSecondary: "#94A3B8",
                placeholder: "#64748B",
                lightBackground: 'rgba(0,255,200,0.08)',
                textViewBorder: "#195352",
                secondary: "#162338",
                secondaryText: "#F8FAFC",
                secondaryBackground: '#142E37',
                success: "#22C55E",
                warning: "#FBBF24",
                error: "#FB7185",
                info: "#10F0CD",
                white: "#FFFFFF",
                black: "#000000",
                grey: "#808080",
                grayLight: "#D3D3D3",
                grayDark: "#A9A9A9",
                interestSelectorBg: '#10CEB3',
                cancel: '#FB7185',
                cancelBackground: '#FB718533',
                chatIcon: '#D9F7F2',
                hotelIcon: '#FBBF23',
                hotelIconBackground: '#FBBF2333',
                danger: '#FF3E76',
                dangerBackground: '#FF3E7633',
                star: '#FDBA12',
        },
};

export const themes = {
        light: LightTheme,
        dark: DarkTheme,
        automatic: LightTheme,
};

export type ThemeKey = keyof typeof themes;